/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rem;
import DAO.PersonaDAO;
import VO.Persona;
/**
 *
 * @author z40L
 */
public class RemIFMDarDeBaja extends javax.swing.JInternalFrame {

    /**
     * Creates new form RemIFMDarDeBaja
     */
    public RemIFMDarDeBaja() {
        initComponents();
        labelNombre.setVisible(false);
        fieldMostrarNombre.setVisible(false);
        botonDarDeBaja.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fieldRut = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldDv = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        labelNombre = new javax.swing.JLabel();
        fieldMostrarNombre = new javax.swing.JTextField();
        botonDarDeBaja = new javax.swing.JButton();

        setClosable(true);
        setTitle("Dar de Baja Personal");

        jLabel1.setText("Rut");

        fieldRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldRutActionPerformed(evt);
            }
        });

        jLabel2.setText("-");

        fieldDv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDvActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        labelNombre.setText("Nombre: ");

        fieldMostrarNombre.setEditable(false);
        fieldMostrarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldMostrarNombreActionPerformed(evt);
            }
        });

        botonDarDeBaja.setText("Dar de Baja");
        botonDarDeBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDarDeBajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonDarDeBaja)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldRut, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldDv, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldMostrarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(fieldDv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(fieldMostrarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonDarDeBaja)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldRutActionPerformed

    private void fieldDvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDvActionPerformed

    private void fieldMostrarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldMostrarNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldMostrarNombreActionPerformed

    private void botonDarDeBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDarDeBajaActionPerformed
        // TODO add your handling code here:
        PersonaDAO personaB = new PersonaDAO();

        int rut = Integer.parseInt(fieldRut.getText());
        int dv  = Integer.parseInt(fieldDv.getText());
        
        personaB.darDeBajaPersona(rut, dv);
    }//GEN-LAST:event_botonDarDeBajaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
        PersonaDAO personaB = new PersonaDAO();
        int rut = Integer.parseInt(fieldRut.getText());
        int dv  = Integer.parseInt(fieldDv.getText());
        Persona personaBuscar = personaB.buscarPersona(rut, dv);
        
        if(personaBuscar != null){
            labelNombre.setVisible(true);
            fieldMostrarNombre.setVisible(true);
            botonDarDeBaja.setVisible(true);
            fieldMostrarNombre.setText(personaBuscar.getNombre() + " " + personaBuscar.getApellidoPat() + " " + personaBuscar.getApellidoMat());
        } else {
            fieldMostrarNombre.setText("La persona no se encuentra.");
            fieldMostrarNombre.setVisible(true);
            labelNombre.setVisible(false);
            botonDarDeBaja.setVisible(false);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDarDeBaja;
    private javax.swing.JTextField fieldDv;
    private javax.swing.JTextField fieldMostrarNombre;
    private javax.swing.JTextField fieldRut;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelNombre;
    // End of variables declaration//GEN-END:variables
}
