/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rem;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

import DAO.PersonaDAO;
import DAO.AfpDAO;
import DAO.ciudadDAO;

import VO.Persona;
import VO.Afp;
import VO.Ciudad;
import java.text.SimpleDateFormat;

/**
 *
 * @author z40L
 */
public class RemIFMAgregar extends javax.swing.JInternalFrame {

    /**
     * Creates new form RemIFMAgregar
     */
    public RemIFMAgregar() {
        initComponents();
        verificacionDV.setVisible(false);
        AfpDAO afp = new AfpDAO();
        ArrayList<Afp> listaAfp = afp.listaDeAfp();
        
        for(Afp a: listaAfp){
            comboAfp.addItem(a.getNombre());
        }
        
        ciudadDAO ciudad = new ciudadDAO();
        ArrayList<Ciudad> listaCiudad = ciudad.listaCiudad();

        for(Ciudad c: listaCiudad) {
            comboCiudad.addItem(c.getNombre());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        fieldNombre = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fieldDV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldApellidoP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fieldApellidoM = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fieldDireccion = new javax.swing.JTextField();
        fieldRut = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        fieldSueldoBase = new javax.swing.JTextField();
        fieldColacion = new javax.swing.JTextField();
        fieldMovilizacion = new javax.swing.JTextField();
        comboCiudad = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        comboAfp = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        verificacionDV = new javax.swing.JTextPane();
        fieldNacimiento2 = new org.jdesktop.swingx.JXDatePicker();

        jButton1.setText("jButton1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setClosable(true);
        setTitle("Agregar Personal");

        jLabel1.setText("Nombre");

        fieldNombre.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                fieldNombreInputMethodTextChanged(evt);
            }
        });
        fieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombreActionPerformed(evt);
            }
        });
        fieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldNombreKeyTyped(evt);
            }
        });

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Rut");

        fieldDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fieldDVMouseExited(evt);
            }
        });
        fieldDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDVActionPerformed(evt);
            }
        });
        fieldDV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldDVKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldDVKeyTyped(evt);
            }
        });

        jLabel3.setText("-");

        jLabel4.setText("Apellido Paterno ");

        fieldApellidoP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldApellidoPKeyTyped(evt);
            }
        });

        jLabel5.setText("Apellido Materno");

        jLabel7.setText("Fecha Nacimiento");

        jLabel8.setText("Dirección");

        fieldApellidoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldApellidoMKeyTyped(evt);
            }
        });

        jLabel9.setText("Ciudad");

        fieldDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDireccionActionPerformed(evt);
            }
        });

        fieldRut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fieldRutMouseExited(evt);
            }
        });
        fieldRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldRutActionPerformed(evt);
            }
        });

        jLabel10.setText("-");

        jLabel11.setText("Sueldo Base");

        jLabel12.setText("Bono Colación");

        jLabel13.setText("Bono Movilización");

        fieldSueldoBase.setText("0");
        fieldSueldoBase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldSueldoBaseKeyTyped(evt);
            }
        });

        fieldColacion.setText("0");
        fieldColacion.setToolTipText("");
        fieldColacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldColacionKeyTyped(evt);
            }
        });

        fieldMovilizacion.setText("0");
        fieldMovilizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldMovilizacionActionPerformed(evt);
            }
        });
        fieldMovilizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldMovilizacionKeyTyped(evt);
            }
        });

        comboCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCiudadActionPerformed(evt);
            }
        });

        jLabel14.setText("AFP");

        comboAfp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAfpActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);

        verificacionDV.setBorder(null);
        verificacionDV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                verificacionDVFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(verificacionDV);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(comboCiudad, javax.swing.GroupLayout.Alignment.LEADING, 0, 274, Short.MAX_VALUE)
                                    .addComponent(fieldDireccion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jButton2))
                                    .addComponent(comboAfp, javax.swing.GroupLayout.Alignment.LEADING, 0, 274, Short.MAX_VALUE)
                                    .addComponent(fieldMovilizacion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldColacion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldSueldoBase, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, 0)
                                .addComponent(jLabel6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldNacimiento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(fieldApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fieldNombre)
                                        .addComponent(fieldApellidoP)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(fieldRut, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(fieldDV, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(11, 11, 11))))))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(fieldDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fieldApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fieldApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fieldNacimiento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(fieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(comboCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fieldSueldoBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(fieldColacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(fieldMovilizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(comboAfp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDVActionPerformed

    private void fieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombreActionPerformed

    private void fieldDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDireccionActionPerformed

    private void fieldRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldRutActionPerformed

    private void fieldMovilizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldMovilizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldMovilizacionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String hola = verificacionDV.getText();
        String chao = fieldDV.getText();
          
        if (hola.equals(chao)==false){
            JOptionPane.showMessageDialog(null, "El RUT ingresado no es válido");
            fieldDV.setText("");
          
        }else
        {    
            int rut                 = Integer.valueOf(fieldRut.getText());
            int dv                  = Integer.valueOf(fieldDV.getText());
            String nombre           = fieldNombre.getText();
            String apellidoP        = fieldApellidoP.getText();
            String apellidoM        = fieldApellidoM.getText();
            //String fechaNacimiento  = fieldNacimiento.getText();
            String fechaNacimiento = new SimpleDateFormat("yyy-MM-dd").format(fieldNacimiento2.getDate());
            String direccion        = fieldDireccion.getText();
            //Object idCiudad =  comboCiudad.getSelectedItem();

            int idCiudad            =  comboCiudad.getSelectedIndex()+1;
            int sueldoBase          = Integer.valueOf(fieldSueldoBase.getText());
            int bonoColacion        = Integer.valueOf(fieldColacion.getText());
            int bonoMovilizacion    = Integer.valueOf(fieldMovilizacion.getText());
            //Object idAfp = comboAfp.getSelectedItem();
            int idAfp               = comboAfp.getSelectedIndex()+1;

            Persona nuevaPersona = new Persona(nombre,apellidoP,apellidoM,direccion,fechaNacimiento,rut,dv,idCiudad,sueldoBase,bonoColacion,bonoMovilizacion,idAfp);

            PersonaDAO daoPersona = new PersonaDAO();
            daoPersona.registrarPersona(nuevaPersona);
        }    

    }//GEN-LAST:event_jButton2ActionPerformed

    private void comboCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCiudadActionPerformed

    private void comboAfpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAfpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAfpActionPerformed

    private void fieldRutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldRutMouseExited
        // TODO add your handling code here:
        int rut = Integer.valueOf(fieldRut.getText());
        
        int[] arr_rut = new int[9];
        int sum = 0 , aux = 0 , cod_ver = 0;
        int i;
        int j=2;
        String cv;
        
        for (i = 0; i < String.valueOf(fieldRut.getText()).length(); i++) {
            arr_rut[i] = rut%10;
            rut = rut/10;
        }
       
        for (i = 0 ; i < String.valueOf(fieldRut.getText()).length();i++){
            if (j>7) j=2;
            sum = sum + (arr_rut[i]*j);
            j++;
        }
        aux = sum;  //se almacema en otra variable porque luego requeriremos este valor.
        sum = sum/11;
        sum = sum*11;   
        aux = aux - sum;
        cod_ver = 11 - aux;
        if (cod_ver == 10 ){
            cv = "K";
        }else if(cod_ver == 11){
            cv = "0";
        }else {
            cv = Integer.toString(cod_ver);
        }
        
       verificacionDV.setText(cv);
    }//GEN-LAST:event_fieldRutMouseExited

    private void verificacionDVFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_verificacionDVFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_verificacionDVFocusLost

    private void fieldDVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldDVMouseExited
        // TODO add your handling code here:   
    //System.out.println("HOLA" + new SimpleDateFormat("yyyy-MM-dd").format(fieldNacimiento2.getDate()));
    }//GEN-LAST:event_fieldDVMouseExited

    private void fieldDVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldDVKeyTyped
        // TODO add your handling code here
        
    }//GEN-LAST:event_fieldDVKeyTyped

    private void fieldDVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldDVKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_fieldDVKeyPressed

    private void fieldNombreInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_fieldNombreInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombreInputMethodTextChanged

    private void fieldNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldNombreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar(); 
        
        if(Character.isDigit(c)) { 
            getToolkit().beep(); 
            evt.consume(); 
        }  
    }//GEN-LAST:event_fieldNombreKeyTyped

    private void fieldApellidoPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldApellidoPKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar(); 
        
        if(Character.isDigit(c)) { 
            getToolkit().beep(); 
            evt.consume(); 
        } 
    }//GEN-LAST:event_fieldApellidoPKeyTyped

    private void fieldApellidoMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldApellidoMKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar(); 
        
        if(Character.isDigit(c)) { 
            getToolkit().beep(); 
            evt.consume(); 
        } 
    }//GEN-LAST:event_fieldApellidoMKeyTyped

    private void fieldSueldoBaseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldSueldoBaseKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar(); 
        
        if(Character.isLetter(c)) { 
            getToolkit().beep(); 
            evt.consume(); 
        } 
    }//GEN-LAST:event_fieldSueldoBaseKeyTyped

    private void fieldColacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldColacionKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar(); 
        
        if(Character.isLetter(c)) { 
            getToolkit().beep(); 
            evt.consume(); 
        } 
    }//GEN-LAST:event_fieldColacionKeyTyped

    private void fieldMovilizacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldMovilizacionKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar(); 
        
        if(Character.isLetter(c)) { 
            getToolkit().beep(); 
            evt.consume(); 
        } 
    }//GEN-LAST:event_fieldMovilizacionKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboAfp;
    private javax.swing.JComboBox<String> comboCiudad;
    private javax.swing.JTextField fieldApellidoM;
    private javax.swing.JTextField fieldApellidoP;
    private javax.swing.JTextField fieldColacion;
    private javax.swing.JTextField fieldDV;
    private javax.swing.JTextField fieldDireccion;
    private javax.swing.JTextField fieldMovilizacion;
    private org.jdesktop.swingx.JXDatePicker fieldNacimiento2;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JTextField fieldRut;
    private javax.swing.JTextField fieldSueldoBase;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane verificacionDV;
    // End of variables declaration//GEN-END:variables

    private boolean format(Date date) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
