/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rem;


import DAO.PersonaDAO;
import DAO.AfpDAO;
import DAO.ciudadDAO;

import VO.Persona;
import VO.Afp;
import VO.Ciudad;
import java.util.ArrayList;


/**
 *
 * @author aniba
 */
public class RemIFMPagoSimple extends javax.swing.JInternalFrame {

    /**
     * Creates new form RemIFMPagoSimple
     */
    public RemIFMPagoSimple() {
        initComponents();
        fieldSueldoBase.setVisible(false);
        fieldBonoColacion.setVisible(false);
        fieldBonoMovilizacion.setVisible(false);
        fieldDescuentoAfp.setVisible(false);
        fieldDescuentoRenta.setVisible(false);
        
        labelSueldoBase.setVisible(false);
        labelBonoColacion.setVisible(false);
        labelBonoMovilizacion.setVisible(false);
        labelDescuentoAfp.setVisible(false);
        labelDescuentoRenta.setVisible(false);
        
        PersonaDAO p = new PersonaDAO();
        ArrayList<Persona> listaPersonas = p.getListaPersonas();
        
        listaPersonas.forEach((i) -> {
            comboPersonas.addItem(i.getNombre()+ " " + i.getApellidoPat() + " " + i.getApellidoMat());
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        comboPersonas = new javax.swing.JComboBox<>();
        botonPago = new javax.swing.JButton();
        labelSueldoBase = new javax.swing.JLabel();
        labelBonoColacion = new javax.swing.JLabel();
        labelBonoMovilizacion = new javax.swing.JLabel();
        labelDescuentoAfp = new javax.swing.JLabel();
        fieldSueldoBase = new javax.swing.JTextField();
        fieldBonoColacion = new javax.swing.JTextField();
        fieldBonoMovilizacion = new javax.swing.JTextField();
        fieldDescuentoAfp = new javax.swing.JTextField();
        labelDescuentoRenta = new javax.swing.JLabel();
        fieldDescuentoRenta = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Realizar Pago");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero ", "Febrero", "Marzo", "Abril", "Mayo ", "Junio ", "Julio ", "Agosto ", "Septiembre ", "Octubre ", "Noviembre ", "Diciembre" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        botonPago.setText("Consultar");
        botonPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPagoActionPerformed(evt);
            }
        });

        labelSueldoBase.setText("Sueldo Base:");

        labelBonoColacion.setText("Bono Colación:");

        labelBonoMovilizacion.setText("Bono Movilización:");

        labelDescuentoAfp.setText("Descuento Afp:");

        fieldSueldoBase.setEditable(false);

        fieldBonoColacion.setEditable(false);

        fieldBonoMovilizacion.setEditable(false);

        fieldDescuentoAfp.setEditable(false);
        fieldDescuentoAfp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDescuentoAfpActionPerformed(evt);
            }
        });

        labelDescuentoRenta.setText("Descuento Renta:");

        fieldDescuentoRenta.setEditable(false);
        fieldDescuentoRenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDescuentoRentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonPago))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelSueldoBase)
                                    .addComponent(labelBonoColacion)
                                    .addComponent(labelBonoMovilizacion)
                                    .addComponent(labelDescuentoAfp)
                                    .addComponent(labelDescuentoRenta))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldSueldoBase, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(fieldBonoColacion)
                                    .addComponent(fieldBonoMovilizacion)
                                    .addComponent(fieldDescuentoAfp)
                                    .addComponent(fieldDescuentoRenta))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonPago))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSueldoBase)
                    .addComponent(fieldSueldoBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBonoColacion)
                    .addComponent(fieldBonoColacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBonoMovilizacion)
                    .addComponent(fieldBonoMovilizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDescuentoAfp)
                    .addComponent(fieldDescuentoAfp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDescuentoRenta)
                    .addComponent(fieldDescuentoRenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void botonPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPagoActionPerformed
        // TODO add your handling code here:
        PersonaDAO p = new PersonaDAO();
        ArrayList<Persona> listaPersonas = p.getListaPersonas();
        Persona personaAux = listaPersonas.get(comboPersonas.getSelectedIndex());
        
        fieldSueldoBase.setVisible(true);
        fieldBonoColacion.setVisible(true);
        fieldBonoMovilizacion.setVisible(true);
        fieldDescuentoAfp.setVisible(true);
        fieldDescuentoRenta.setVisible(true);
        
        labelSueldoBase.setVisible(true);
        labelBonoColacion.setVisible(true);
        labelBonoMovilizacion.setVisible(true);
        labelDescuentoAfp.setVisible(true);
        labelDescuentoRenta.setVisible(true);
        
        fieldSueldoBase.setText(Integer.toString(personaAux.getSueldoBase()));
        fieldBonoColacion.setText(Integer.toString(personaAux.getBonoColacion()));
        fieldBonoMovilizacion.setText(Integer.toString(personaAux.getBonoMovilizacion()));
        
        
    }//GEN-LAST:event_botonPagoActionPerformed

    private void fieldDescuentoAfpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDescuentoAfpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDescuentoAfpActionPerformed

    private void fieldDescuentoRentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDescuentoRentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDescuentoRentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPago;
    private javax.swing.JComboBox<String> comboPersonas;
    private javax.swing.JTextField fieldBonoColacion;
    private javax.swing.JTextField fieldBonoMovilizacion;
    private javax.swing.JTextField fieldDescuentoAfp;
    private javax.swing.JTextField fieldDescuentoRenta;
    private javax.swing.JTextField fieldSueldoBase;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelBonoColacion;
    private javax.swing.JLabel labelBonoMovilizacion;
    private javax.swing.JLabel labelDescuentoAfp;
    private javax.swing.JLabel labelDescuentoRenta;
    private javax.swing.JLabel labelSueldoBase;
    // End of variables declaration//GEN-END:variables
}
