/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rem;

import DAO.RemuneracionDAO;
import VO.Remuneracion;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author MaríaJosée
 */
public class RemIFMConsultarPago extends javax.swing.JInternalFrame {

    /**
     * Creates new form RemIFMConsultarPago
     */
    DecimalFormat formatea = new DecimalFormat("###,###.##");
    
    public RemIFMConsultarPago() {
        initComponents();
        mostrarListaPagosOnTable();
    }
    public void mostrarListaPagosOnTable(){
        RemuneracionDAO daoPago = new RemuneracionDAO();
        
        DefaultTableModel model = (DefaultTableModel)JTablaPagos.getModel();
        Object[] row = new Object[15];
        ArrayList<Remuneracion> listaPagos = daoPago.getListaPagos();
        for(Remuneracion pago: listaPagos){
            row[0]  = pago.getPersonaRut();
            row[1]  = formatea.format(pago.getMontoLiquido());
            row[2]  = formatea.format(pago.getMontoBruto());
            row[3]  = formatea.format(pago.getSeguroCesantia());
            row[4]  = formatea.format(pago.getDescuentoAfp());
            row[5]  = formatea.format(pago.getDescuentoRenta());
            row[6]  = formatea.format(pago.getComisiones());
            row[7]  = pago.getFecha();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTablaPagos = new javax.swing.JTable();

        setTitle("Consultar Pagos");

        JTablaPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RUT", "Sueldo Líquido", "Sueldo Bruto", "Seguro Cesantía", "Descuento AFP", "Impuesto a la Renta", "Comisiones", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JTablaPagos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(JTablaPagos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTablaPagos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
